# Generated by Django 5.1.3 on 2026-05-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal_avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalavaliacao',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
