# Generated by Django 5.1.3 on 2026-09-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal_avaliacao', '0002_modalavaliacao_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalavaliacao',
            name='comentario',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
