# Generated by Django 5.1.3 on 2026-10-09 17:31

from django.conf import settings
from django.db import migrations, models


def preserve_latest_reviews(apps, schema_editor):
    Review = apps.get_model("modal_avaliacao", "ModalAvaliacao")
    seen = set()
    archived = []
    for row in (
        Review.objects.using(schema_editor.connection.alias)
        .order_by("user_id", "local_id", "-data_resposta", "-pk")
        .values("pk", "user_id", "local_id")
        .iterator()
    ):
        pair = (row["user_id"], row["local_id"])
        if pair in seen:
            archived.append(row["pk"])
        seen.add(pair)
    for offset in range(0, len(archived), 500):
        Review.objects.using(schema_editor.connection.alias).filter(pk__in=archived[offset : offset + 500]).update(
            is_current=False
        )


class Migration(migrations.Migration):

    dependencies = [
        ("locais", "0007_visitarecente_arrival_confirmed"),
        ("modal_avaliacao", "0003_alter_modalavaliacao_comentario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="modalavaliacao",
            name="comment_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modalavaliacao",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="modalavaliacao",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="modalavaliacao",
            name="verified_author",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(preserve_latest_reviews, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="modalavaliacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("user", "local"),
                name="one_current_review_per_user_place",
            ),
        ),
    ]
