# Generated by Django 5.1.3 on 2026-10-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal_avaliacao', '0004_modalavaliacao_comment_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalavaliacao',
            name='survey_completed',
            field=models.BooleanField(default=False),
        ),
    ]
