# Generated by Django 5.1.3 on 2026-05-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='banheiro_acessivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='local',
            name='cao_guia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='local',
            name='cardapio_braille',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='local',
            name='mesa_acessivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='local',
            name='rampa_acesso',
            field=models.BooleanField(default=False),
        ),
    ]
