# Generated by Django 5.1.3 on 2026-05-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0002_local_banheiro_acessivel_local_cao_guia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='imagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
