# Generated by Django 5.1.3 on 2026-05-31 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0003_local_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaRecente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='locais.local')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visita_recente',
                'ordering': ['-data_visita'],
                'managed': True,
            },
        ),
    ]
