# Generated by Django 5.1.3 on 2026-09-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0004_visitarecente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='imagem',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
