# Generated by Django 5.1.3 on 2026-10-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0005_alter_local_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='categoria',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='local',
            name='osm_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
