# Generated by Django 5.1.3 on 2026-10-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0006_local_categoria_local_osm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitarecente',
            name='arrival_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
