# Generated by Django 5.1.3 on 2026-06-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='compartilhar_localizacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='historico_visivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idioma',
            field=models.CharField(default='pt_BR', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='impedir_autobloqueio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mostrar_avaliacoes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil_publico',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='permitir_sugestoes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='unidade_distancia',
            field=models.CharField(default='KM', max_length=5),
        ),
    ]
