"""
Django settings for acessoja project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Variáveis de ambiente (django-environ)
# Lê o arquivo .env na raiz do projeto (se existir) e cai para variáveis de
# ambiente reais do sistema/CI quando não existir. Nunca versionar o .env.
# ---------------------------------------------------------------------------
env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Obrigatório vir do ambiente (.env local ou variável de ambiente no CI/deploy).
# Sem valor padrão de propósito: se não for definido, a aplicação deve falhar
# ao subir, em vez de rodar com uma chave insegura.
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# Sem '*' como padrão: em produção, ALLOWED_HOSTS deve ser definido
# explicitamente via variável de ambiente.
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'acessoja',
    'usuarios',
    'rest_framework',
    'locais',
    'djoser',
    'corsheaders',
    'modal_avaliacao',
    'avaliacao',

    # Documentacao viva da API (OpenAPI 3 + Swagger UI)
    'drf_spectacular',
    'drf_spectacular_sidecar',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'acessoja.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'acessoja.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASE_URL define o banco por completo (usuário, senha, host, porta, nome).
# Aceita tanto PostgreSQL (postgresql://...) quanto SQLite (sqlite:///./arquivo.sqlite3),
# o que já cobre o caso do CI, que roda com DATABASE_URL=sqlite:///./db_ci.sqlite3.
DATABASES = {
    'default': env.db('DATABASE_URL'),
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [],
    # Gera o schema OpenAPI a partir do proprio codigo.
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

DJOSER = {
    'USER_ID_FIELD': 'id_usuario',
}

AUTH_USER_MODEL = 'usuarios.Usuario'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/usuarios/login/'

AUTHENTICATION_BACKENDS = [
    'usuarios.backends.UsuarioBackend',  # Caminho para o seu backend personalizado
    'django.contrib.auth.backends.ModelBackend',  # Mantém o backend padrão do Django
]

CORS_ALLOW_ALL_ORIGINS = True

# ---------------------------------------------------------------------------
# Documentacao da API (drf-spectacular)
# Swagger UI: /api/docs/  |  ReDoc: /api/redoc/  |  OpenAPI 3: /api/schema/
# ---------------------------------------------------------------------------
SPECTACULAR_SETTINGS = {
    'TITLE': 'AcessoJá API',
    'DESCRIPTION': (
        'API REST do **AcessoJá** — plataforma para encontrar e avaliar a '
        'acessibilidade de estabelecimentos e locais públicos.\n\n'
        '## Como usar\n\n'
        'O app Flutter identifica o usuário pelo campo `nome` (não pelo e-mail). '
        'Faça `POST /api/login/` para validar as credenciais e, nas rotas que '
        'pedem autoria, envie `nome` ou `nome_usuario` no corpo da requisição.\n\n'
        '> **Atenção:** hoje as rotas de escrita usam `AllowAny` e a autoria vem '
        'do corpo da requisição, não de um token. Isso está documentado como é, '
        'não como deveria ser — fechar isso é o cartão de segurança da sprint.\n\n'
        '## Convenções\n\n'
        '- Respostas em JSON UTF-8.\n'
        '- Datas em ISO-8601.\n'
        '- Erros de validação retornam `400` com o mapa de campos inválidos.\n'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
    'ENUM_NAME_OVERRIDES': {
        'RespostaAcessibilidadeEnum': 'modal_avaliacao.models.RESPOSTAS',
    },
    # Assets servidos localmente: a doc abre sem depender de CDN.
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'filter': True,
    },
    'TAGS': [
        {'name': 'Autenticação', 'description': 'Login e rotas de conta do Djoser.'},
        {'name': 'Locais', 'description': 'Locais e filtros de acessibilidade.'},
        {'name': 'Visitas', 'description': 'Histórico de locais visitados pelo usuário.'},
        {'name': 'Avaliações', 'description': 'Avaliações de acessibilidade dos locais.'},
        {'name': 'Usuários', 'description': 'Perfil, senha e foto do usuário.'},
    ],
    'CONTACT': {
        'name': 'Equipe AcessoJá',
        'url': 'https://github.com/acessoja/acessoja-app',
    },
    'LICENSE': {'name': 'Projeto educacional'},
}
